import random

print("MOTHER:")
orange1m = "X^" + input("First X has o or O linked? ")
orange2m = "X^" + input("Second X has o or O linked? ")
base1m = input("First base gene: ")
base2m = input("Second base gene: ")
dilution1m = input("First dilution gene: ")
dilution2m = input("Second dilution gene: ")
agouti1m = input("First agouti gene: ")
agouti2m = input("Second agouti gene: ")
fur1m = input("First fur length gene: ")
fur2m = input("Second fur length gene: ")
color1m = input("First colorpoint gene: ")
color2m = input("Second colorpoint gene: ")
mc1m = input("First tabby gene: ")
mc2m = input("Second tabby gene: ")
wb1m = input("First wideband gene: ")
wb2m = input("Second wideband gene: ")
ticked1m = input("First ticked gene: ")
ticked2m = input("Second ticked gene: ")
white1m = input("First white spottings gene: ")
white2m = input("Second white spottings gene: ")
silver1m = input("First silver gene: ")
silver2m = input("Second silver gene: ")
fullw1m = input("First full white gene: ")
fullw2m = input("Second full white gene: ")
spottingm = input("Spotting? (1=yes, 0=no): ")

print("FATHER: ")
orange1f = "X^" + input("X has o or O linked? ")
orange2f = "Y"
base1f = input("First base gene: ")
base2f = input("Second base gene: ")
dilution1f = input("First dilution gene: ")
dilution2f = input("Second dilution gene: ")
agouti1f = input("First agouti gene: ")
agouti2f = input("Second agouti gene: ")
fur1f = input("First fur length gene: ")
fur2f = input("Second fur length gene: ")
color1f = input("First colorpoint gene: ")
color2f = input("Second colorpoint gene: ")
mc1f = input("First tabby gene: ")
mc2f = input("Second tabby gene: ")
wb1f = input("First wideband gene: ")
wb2f = input("Second wideband gene: ")
ticked1f = input("First ticked gene: ")
ticked2f = input("Second ticked gene: ")
white1f = input("First white spottings gene: ")
white2f = input("Second white spottings gene: ")
silver1f = input("First silver gene: ")
silver2f = input("Second silver gene: ")
fullw1f = input("First full white gene: ")
fullw2f = input("Second full white gene: ")
spottingf = input("Spotting? (1=yes, 0=no): ")

amount = int(input("How many kits? "))
i = 1
while i <= amount: 
    print(f"KIT {i}:")
    orange1 = random.choice([orange1m, orange2m])
    orange2 = random.choice([orange1f, orange2f])
    print(f"Orange: {orange1}/{orange2}")
    base1 = random.choice([base1m, base1m])
    base2 = random.choice([base1f, base2f])
    print(f"Base: {base1}/{base2}")
    dilution1 = random.choice([dilution1m, dilution2m])
    dilution2 = random.choice([dilution1f, dilution2f])
    print(f"Dilution: {dilution1}/{dilution2}")
    agouti1 = random.choice([agouti1m, agouti2m])
    agouti2 = random.choice([agouti1f, agouti2f])
    print(f"Agouti: {agouti1}/{agouti2}")
    fur1 = random.choice([fur1m, fur2m])
    fur2 = random.choice([fur1f, fur2f])
    print(f"Fur length: {fur1}/{fur2}")
    color1 = random.choice([color1m, color2m])
    color2 = random.choice([color1f, color2f])
    print(f"Colorpoint: {color1}/{color2}")
    mc1 = random.choice([mc1m, mc2m])
    mc2 = random.choice([mc1f, mc2f])
    print(f"Tabby: {mc1}/{mc2}")
    wb1 = random.choice([wb1m, wb2m])
    wb2 = random.choice([wb1f, wb2f])
    print(f"Wideband: {wb1}/{wb2}")
    ticked1 = random.choice([ticked1m, ticked2m])
    ticked2 = random.choice([ticked1f, ticked2f])
    print(f"Ticked: {ticked1}/{ticked2}")
    white1 = random.choice([white1m, white2m])
    white2 = random.choice([white1f, white2f])
    print(f"White spotting: {white1}/{white2}")
    silver1 = random.choice([silver1m, silver2m])
    silver2 = random.choice([silver1f, silver2f])
    print(f"Silver: {silver1}/{silver2}")
    fullw1 = random.choice([fullw1m, fullw2m])
    fullw2 = random.choice([fullw1f, fullw2f])
    print(f"Full white: {fullw1}/{fullw2}")
    spotting = random.choice([spottingf, spottingm])
    print(f"Spotting (1=present, 0=absent): {spotting}")
    i += 1